/*******************************************************************************
 **NOTE** This code was generated by a tool and will occasionally be
 overwritten. We welcome comments and issues regarding this code; they will be
 addressed in the generation tool. If you wish to submit pull requests, please
 do so for the templates in that tool.

 This code was generated by Vipr (https://github.com/microsoft/vipr) using
 the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

 Copyright (c) Microsoft Corporation. All Rights Reserved.
 Licensed under the Apache License 2.0; see LICENSE in the source repository
 root for authoritative license information.﻿
 ******************************************************************************/
package com.microsoft.services.outlook;

import com.google.gson.annotations.SerializedName;
import com.microsoft.services.orc.core.ODataBaseEntity;


/**
 * The type Entity.
 */
public class Entity extends ODataBaseEntity {

    private static final String DELETED_REASON = "deleted";

    public Entity() {
        setODataType("#Microsoft.OutlookServices.Entity");
    }

    private String Id;

    @SerializedName("id")
    private String deleteId;

    private String reason;

    /**
     * Gets the Id.
     *
     * @return the String
     */
    public String getId() {
        return this.Id;
    }

    /**
     * Sets the Id.
     *
     * @param value the String
     */
    public void setId(String value) {
        this.Id = value;
        valueChanged("Id", value);

    }

    public String getDeleteId() {
        if (isDeleted() && deleteId != null) {
            return deleteId.split("'")[1];
        }
        return "";
    }


    public boolean isDeleted() {
        return DELETED_REASON.equalsIgnoreCase(reason);
    }
}

